In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 80.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 KB 45.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 58.3 MB/s eta 0:00:00
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully uninstalled flatbuffers-1.12
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: tensorboard
    Found existing i

In [3]:
import pandas as pd

In [5]:
data = pd.read_csv("/content/drive/MyDrive/IMDB 50k records/IMDB Dataset.csv")

In [6]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [8]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
data['review'].str.len()

0        1761
1         998
2         926
3         748
4        1317
         ... 
49995    1008
49996     642
49997    1280
49998    1234
49999     678
Name: review, Length: 50000, dtype: int64

In [12]:
data['review'] = data['review'].str.lower()
data['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [13]:
# removing HTML tags
import re
def remove_html_tags(text):
    re_html = re.compile('<.*?>')
    return re_html.sub(r'', text)

In [14]:
data['review'] = data['review'].apply(remove_html_tags)

In [15]:
# removing URLS
def remove_url(text):
    re_url = re.compile('https?://\S+|www\.\S+')
    return re_url.sub('', text)

In [16]:
data['review'] = data['review'].apply(remove_url)

In [17]:
# removing stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords_english = stopwords.words('english')


def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords_english:
            continue
        else:
            new_text.append(word)

    return ' '.join(new_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [20]:
data['review'] = data['review'].apply(remove_stopwords)
data['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. filming technique...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...                        
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    i'm going disagree previous comment side malti...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 50000, dtype: object

In [21]:
# stemming
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def perform_stemming(text):
    new_text = [ps.stem(word) for word in text.split()]
    return ' '.join(new_text)

In [22]:
data['updated_review'] = data['review'].apply(perform_stemming)

In [23]:
len(data['updated_review'].unique())

49578

In [24]:
### Vocabulary size
voc_size=50000

In [25]:
words = []

In [26]:
words = data['updated_review'].copy()

In [27]:
words

0        one review mention watch 1 oz episod hooked. r...
1        wonder littl production. film techniqu unassum...
2        thought wonder way spend time hot summer weeke...
3        basic there' famili littl boy (jake) think the...
4        petter mattei' "love time money" visual stun f...
                               ...                        
49995    thought movi right good job. creativ origin fi...
49996    bad plot, bad dialogue, bad acting, idiot dire...
49997    cathol taught parochi elementari school nuns, ...
49998    i'm go disagre previou comment side maltin one...
49999    one expect star trek movi high art, fan expect...
Name: updated_review, Length: 50000, dtype: object

In [28]:
len(words[1])

628

In [29]:
onehot_repr=[one_hot(sent,voc_size)for sent in words] 
print(onehot_repr)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [30]:
onehot_repr

[[35823,
  7868,
  17689,
  15045,
  4420,
  36328,
  34568,
  34581,
  20298,
  20795,
  31471,
  41918,
  1198,
  10533,
  34293,
  35723,
  36328,
  3691,
  15036,
  33328,
  1289,
  41000,
  20298,
  4468,
  40273,
  43582,
  41918,
  42889,
  20834,
  16756,
  36877,
  42889,
  13664,
  29994,
  27350,
  27047,
  25987,
  1289,
  12878,
  9814,
  41868,
  4468,
  35721,
  26009,
  36328,
  13245,
  35728,
  10650,
  3639,
  9218,
  3238,
  28676,
  36222,
  28497,
  40766,
  33925,
  1246,
  39238,
  31031,
  20825,
  26091,
  16851,
  6006,
  47896,
  19604,
  32031,
  34859,
  32234,
  11460,
  32008,
  1343,
  44936,
  12526,
  10902,
  38738,
  13439,
  8953,
  46672,
  21090,
  6852,
  46310,
  43891,
  44712,
  5685,
  4530,
  6644,
  17037,
  43541,
  21690,
  10219,
  20656,
  9971,
  32960,
  14889,
  40615,
  42889,
  32238,
  7627,
  49210,
  42889,
  22880,
  26776,
  41669,
  43141,
  5807,
  39533,
  43111,
  26776,
  6786,
  26776,
  26214,
  36328,
  24289,
  11006

In [31]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
## pre padding
sent_length=1000
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0 ... 36749 15142 15634]
 [    0     0     0 ... 40370 20070 23398]
 [    0     0     0 ... 40273 36007 14154]
 ...
 [    0     0     0 ... 39159 27582 45299]
 [    0     0     0 ...  6683 15448 45686]
 [    0     0     0 ... 26126 31126  3823]]


In [34]:
## 10 feature dimesnions
dim=10

In [35]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [36]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# model.compile('adam','mse')
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1000, 10)          500000    
                                                                 
 lstm (LSTM)                 (None, 100)               44400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 544,501
Trainable params: 544,501
Non-trainable params: 0
_________________________________________________________________
None


In [37]:
X = embedded_docs
y = data['sentiment']

In [38]:
len(embedded_docs)

50000

In [39]:
data['sentiment'].shape

(50000,)

In [40]:
type(embedded_docs)

numpy.ndarray

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()
y = le.fit_transform(y)

In [43]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [44]:
X_final=embedded_docs
y_final=np.array(y)

In [45]:
X_final.shape,y_final.shape

((50000, 1000), (50000,))

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [47]:
X_train[0]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

In [48]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
524/524 [==============================] - 119s 212ms/step - loss: 0.4401 - accuracy: 0.7921 - val_loss: 0.2923 - val_accuracy: 0.8803
Epoch 2/10
524/524 [==============================] - 73s 139ms/step - loss: 0.2139 - accuracy: 0.9199 - val_loss: 0.2784 - val_accuracy: 0.8866
Epoch 3/10
524/524 [==============================] - 55s 106ms/step - loss: 0.1451 - accuracy: 0.9488 - val_loss: 0.3317 - val_accuracy: 0.8827
Epoch 4/10
524/524 [==============================] - 45s 86ms/step - loss: 0.0938 - accuracy: 0.9697 - val_loss: 0.3658 - val_accuracy: 0.8682
Epoch 5/10
524/524 [==============================] - 50s 95ms/step - loss: 0.0682 - accuracy: 0.9779 - val_loss: 0.4394 - val_accuracy: 0.8720
Epoch 6/10
524/524 [==============================] - 37s 71ms/step - loss: 0.0444 - accuracy: 0.9871 - val_loss: 0.5372 - val_accuracy: 0.8671
Epoch 7/10
524/524 [==============================] - 36s 68ms/step - loss: 0.0443 - accuracy: 0.9858 - val_loss: 0.5168 - val_accur

In [49]:
y_pred = model.predict(X_test)

516/516 [==============================] - 8s 15ms/step


In [50]:
y_pred = np.where(y_pred>0.5,1,0)

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8617575757575757

In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.87      0.86      8208
           1       0.87      0.86      0.86      8292

    accuracy                           0.86     16500
   macro avg       0.86      0.86      0.86     16500
weighted avg       0.86      0.86      0.86     16500

